### ISSUE TITLE
Modules not compiling on Ubuntu 24.04 and Linux 6.8.0-40 lowlatency

### ISSUE THREAD

**Issue by serpastorg** [jvillavi/vmware17-ubuntu24.04#1]
I've just updated to 6.8.0-40 today and it's not compiling.
Here's the console:

![Captura desde 2024-08-12 13-45-13](https://github.com/user-attachments/assets/ecc60a4a-7fff-4d7c-9256-e2a910079a4b)

Thank you a lot :)

**Comment by jvillavi** [comment]
Assuming it worked before, just do a make clean before running the script again. This is intended to work with vanilla ubuntu kernel headers, but you can always try...

**Comment by serpastorg** [comment]
I did make clean, and it didn't work also.
Thanks for your time.
The output is the same

**Comment by serpastorg** [comment]
It works right now. One must erase the folder and clone it again. By doing this it worked... Clone it and make! :)
I'll mark it as solved :D

**Comment by jvillavi** [comment]
Added make clean to the main script. It should compile every time from scratch. Thanks @serpastorg

**Comment by serpastorg** [comment]
There's a thing I must say. For it to work it's needed to be running the kernel you're compiling. I think that was my problem. I didn't realize I haven't reset the computer prior to try to compile the kernel. That was my mistake.
The kernel module compiled flawlessly after reseting
